name: Github Actions Test

on:
  push:
    branches:
      - main

jobs:
    echo-job:
      runs-on: ubuntu-latest
      steps:
        - name: Run Hello world
          run: echo "Hello world & Acada C2 Guys"
          
        - run: sleep 30