name: Deploy Techmax Web

on:
  push:
    branches:
      - main

jobs:
    Build2DH:
      runs-on: aws-runner
      steps:
        - uses: actions/checkout@v7

        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Build techmax Image
          run: docker build . --file Dockerfile --tag kniru/techmax-c2:latest

        - name: Push Image to DockerHub
          run: docker push kniru/techmax-c2:latest

    Build2ECR:
      runs-on: aws-runner
      steps:
        - uses: actions/checkout@v7

        - name: Build techmax Image
          run: docker build . --file Dockerfile --tag techmax-c2:latest

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.2.3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ca-central-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Push Image to ECR
          run: |
             docker tag techmax-c2:latest ${{steps.login-ecr.outputs.registry}}/techmax-web:${{github.sha}}
             docker push ${{steps.login-ecr.outputs.registry}}/techmax-web:${{github.sha}}
      outputs:
            image: ${{steps.login-ecr.outputs.registry}}/techmax-web:${{github.sha}}
            registry: ${{steps.login-ecr.outputs.registry}}

    Deploy:
      needs: [Build2ECR, Build2DH]
      runs-on: aws-runner

      steps:
        - name: Deploy To EC2
          uses: appleboy/ssh-action@v1
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SHA: ${{ github.sha }}
            IMAGE: ${{needs.Build2ECR.outputs.image}}
            REGISTRY: ${{needs.Build2ECR.outputs.registry}}

          with:
            host: ${{ secrets.DOCKER_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,SHA,IMAGE,REGISTRY
            script: |
                sudo apt install unzip -y || true
                curl -fsSL https://awscli.amazonaws.com/v2/install.sh | bash || true
                export PATH=$PATH:/home/ubuntu/.local/bin
                export AWS_DEFAULT_REGION=ca-central-1
                aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin "$REGISTRY"
                docker pull "$IMAGE"
                docker rm -f techmax-web || true
                docker run -d -p 80:80 --name techmax-web "$IMAGE"