name: Deploy Techmax Web

on:
  push:
    branches:
      - main

jobs:
    Build2DH:
      runs-on: aws-runner
      steps:
        - uses: actions/checkout@v7

        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Build techmax Image
          run: docker build . --file Dockerfile --tag kniru/techmax-c2:latest

        - name: Push Image to DockerHub
          run: docker push kniru/techmax-c2:latest

    Build2ECR:
      runs-on: aws-runner
      steps:
        - uses: actions/checkout@v7

        - name: Build techmax Image
          run: docker build . --file Dockerfile --tag techmax-c2:latest

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.2.3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ca-central-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Push Image to ECR
          run: |
             docker tag techmax-c2:latest ${{steps.login-ecr.outputs.registry}}/techmax-web:${{github.sha}}
             docker push ${{steps.login-ecr.outputs.registry}}/techmax-web:${{github.sha}}

    # Deploy:
    #   runs-on: aws-runner

    #   steps:
    #     - name: Docker pull image
    #       run: docker pull kniru/techmax-website:latest

    #     - name: Remove existing container
    #       run: docker rm -f techmax-acada || true

    #     - name: Run pulled Image
    #       run: docker run -d --name techmax-acada -p 80:80 kniru/techmax-website:latest
