name: Github Actions Test

on:
    workflow_dispatch:

jobs:
    Job-1:
      runs-on: aws-self-hosted
      steps:
        - name: Run Hello world
          run: echo "Hello world & Acada C2 Guys"
        - run: sleep 10

    Job-2:
        runs-on: aws-self-hosted
        needs: Job-1
        steps:
            - name: Caveat
              run: echo "Do your Assignment !!!!"
              
            - name: I want to sleep
              run: sleep 10

    Job-3:
        runs-on: aws-self-hosted
        needs: Job-2
        steps:
            - name: Caveat
              run: echo "Do your Assignment !!!!"
              
            - name: I want to sleep
              run: sleep 10